<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>WeiDoctor</AssemblyName>
    <RootNamespace>WeiDoctor</RootNamespace>
    <LangVersion>latest</LangVersion>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
    <Sts2InstallDir Condition="'$(Sts2InstallDir)' == ''">C:/Program Files (x86)/Steam/steamapps/common/Slay the Spire 2</Sts2InstallDir>
    <RitsuLibDir Condition="'$(RitsuLibDir)' == ''">C:/Program Files (x86)/Steam/steamapps/workshop/content/2868840/3747602295/lib/0.111.0</RitsuLibDir>
  </PropertyGroup>

  <ItemGroup>
    <Reference Include="sts2">
      <HintPath>$(Sts2InstallDir)/data_sts2_windows_x86_64/sts2.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="GodotSharp">
      <HintPath>$(Sts2InstallDir)/data_sts2_windows_x86_64/GodotSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>$(Sts2InstallDir)/data_sts2_windows_x86_64/0Harmony.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="STS2-RitsuLib">
      <HintPath>$(RitsuLibDir)/STS2-RitsuLib.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>
</Project>

